### ISSUE TITLE
Краш при нажатии  "Добавить открытку" на главной, при наличии фотографов в базе данных.

### ISSUE THREAD

**Issue by ARK215** [okolobaxa/postcards#10]
![image](https://cloud.githubusercontent.com/assets/13455967/8891377/98aaf05a-332f-11e5-89f3-2695965f9624.png)

**Comment by okolobaxa** [comment]
fixed in https://github.com/oldsaratov/postcards/commit/5b5c014c3c95fa0afb41e15d95bbc401c2d63e1d
