### ISSUE TITLE
Краш при переходе в "Открытки" при наличии фотографов в базе данных.

### ISSUE THREAD

**Issue by ARK215** [okolobaxa/postcards#4]
Думаю, там и в издательствах тоже косяк может быть.
![image](https://cloud.githubusercontent.com/assets/13455967/8891200/96cadc2a-3328-11e5-9947-71dc8caeb944.png)

**Comment by okolobaxa** [comment]
fixed in https://github.com/oldsaratov/postcards/commit/5b5c014c3c95fa0afb41e15d95bbc401c2d63e1d
