### ISSUE TITLE
Limit for lenght of textbox string

### ISSUE THREAD

**Issue by ARK215** [okolobaxa/postcards#5]
*При добавлении имени автора - написать в строке очень много символов (у меня больше 300)

Предлагаю сделать ограничение в 30 символов, чтобы влезало на любой экран красиво

![image](https://cloud.githubusercontent.com/assets/13455967/8891233/121f8f3c-332a-11e5-9921-5810bc3808f3.png)

**Comment by okolobaxa** [comment]
implemented
