### ISSUE TITLE
Только 3 фотографа отображаются на странице

### ISSUE THREAD

**Issue by ARK215** [okolobaxa/postcards#6]
*Добавить несколько авторов
*Наблюдать

Ожидаемое: Все авторы отображаются
![image](https://cloud.githubusercontent.com/assets/13455967/8891263/213a3b74-332b-11e5-8e21-62900162d270.png)

**Comment by okolobaxa** [comment]
fix in https://github.com/oldsaratov/postcards/commit/b9bfef76cfb0a092daa7c0eb6db7c7c57d9863ce
